runtime: nodejs16

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  MONGODB_URI: "YOUR_MONGODB_ATLAS_CONNECTION_STRING"
  JWT_SECRET: "YOUR_PRODUCTION_JWT_SECRET"
  JWT_EXPIRE: "30d"
  EMAIL_SERVICE: "gmail"
  EMAIL_USERNAME: "enjoyboking@gmail.com"
  EMAIL_PASSWORD: "YOUR_EMAIL_APP_PASSWORD"
  EMAIL_FROM: "enjoyboking@gmail.com"
  TWILIO_ACCOUNT_SID: "YOUR_TWILIO_SID"
  TWILIO_AUTH_TOKEN: "YOUR_TWILIO_TOKEN"
  TWILIO_PHONE_NUMBER: "YOUR_TWILIO_PHONE"
  STRIPE_SECRET_KEY: "YOUR_STRIPE_SECRET_KEY"
  STRIPE_WEBHOOK_SECRET: "YOUR_STRIPE_WEBHOOK_SECRET"
  MAX_IMAGE_SIZE: "10485760"
  MAX_VIDEO_SIZE: "31457280"
